
-- DW Bursátil - STAGING AREA
-- Oracle Autonomous Database

-- Note: the tables replicates the raw
-- structure of the sources.

CREATE TABLE STG_DAILY_PRICES (
    SYMBOL VARCHAR2(10),
    TRADE_DATE DATE,
    OPEN_PRICE NUMBER(12,4),
    HIGH_PRICE NUMBER(12,4),
    LOW_PRICE NUMBER(12,4),
    CLOSE_PRICE NUMBER(12,4),
    VOLUME NUMBER(15),
    LOAD_TS TIMESTAMP DEFAULT SYSTIMESTAMP,
    SOURCE_NAME VARCHAR2(50) DEFAULT 'ALPHAVANTAGE_DAILY'
);

CREATE TABLE STG_COMPANY_OVERVIEW (
    SYMBOL VARCHAR2(10),
    COMPANY_NAME VARCHAR2(200),
    EXCHANGE VARCHAR2(20),
    SECTOR VARCHAR2(100),
    INDUSTRY VARCHAR2(150),
    COUNTRY VARCHAR2(50),
    MARKET_CAP NUMBER(20),
    DESCRIPTION VARCHAR2(4000),
    LOAD_TS TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE STG_SP500_COMPONENTS (
    SYMBOL VARCHAR2(10),
    SECURITY_NAME VARCHAR2(200),
    GICS_SECTOR VARCHAR2(100),
    GICS_SUB_INDUSTRY VARCHAR2(150),
    HQ_LOCATION VARCHAR2(150),
    DATE_ADDED VARCHAR2(20),
    CIK VARCHAR2(10),
    FOUNDED VARCHAR2(30),
    LOAD_TS TIMESTAMP DEFAULT SYSTIMESTAMP
);

SELECT * FROM STG_DAILY_PRICES ORDER BY trade_date DESC;
SELECT * FROM STG_COMPANY_OVERVIEW;
SELECT * FROM STG_SP500_COMPONENTS;

