-- ============================================================
-- DELIVERY 2 - Stock Market DW - OLAP QUERIES
-- Oracle Autonomous Database
-- Run against the Star Schema model after running the ETL.
-- Includes: time series, pattern matching (MATCH_RECOGNIZE),
-- OLAP extensions (ROLLUP, CUBE), and advanced window functions.
-- ============================================================

-- ============================================================
-- SECTION A: TIME-SERIES ANALYSIS
-- ============================================================

-- A.1 Cumulative return from the first quote per symbol
-- Uses FIRST_VALUE to anchor the base price at t=0
SELECT c.SYMBOL, c.COMPANY_NAME, d.FULL_DATE, f.CLOSE_PRICE,
       FIRST_VALUE(f.CLOSE_PRICE) OVER (PARTITION BY f.COMPANY_KEY
           ORDER BY f.DATE_KEY ROWS UNBOUNDED PRECEDING) AS BASE_PRICE,
       ROUND((f.CLOSE_PRICE / FIRST_VALUE(f.CLOSE_PRICE) OVER (
           PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
           ROWS UNBOUNDED PRECEDING) - 1) * 100, 2) AS CUMULATIVE_RETURN_PCT
FROM FACT_DAILY_QUOTE f
JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY --AND c.IS_CURRENT = 'Y'
JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
ORDER BY c.SYMBOL, d.FULL_DATE;

SELECT f.SMA_20, c.SYMBOL, d.YEAR_NUM, d.MONTH_NUM
FROM FACT_DAILY_QUOTE f
INNER JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY
INNER JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
WHERE c.SYMBOL = 'JPM' AND d.YEAR_NUM IN (2024, 2025, 2026);

-- A.2 Average monthly closing price with hierarchical ROLLUP
-- Hierarchy: Year > Month > Symbol
-- GROUPING() identifies subtotal/total rows
SELECT GROUPING(d.YEAR_NUM) AS G_YEAR,
       GROUPING(d.MONTH_NUM) AS G_MONTH,
       GROUPING(c.SYMBOL) AS G_SYMBOL,
       NVL(TO_CHAR(d.YEAR_NUM), '(ALL)') AS YEAR,
       NVL(TO_CHAR(d.MONTH_NUM, 'FM00'), '(ALL)') AS MONTH,
       NVL(c.SYMBOL, '(ALL)') AS SYMBOL,
       ROUND(AVG(f.CLOSE_PRICE), 2) AS AVG_CLOSE,
       ROUND(SUM(f.VOLUME) / 1e6, 2) AS VOLUME_MILLIONS
FROM FACT_DAILY_QUOTE f
JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY --AND c.IS_CURRENT = 'Y'
GROUP BY ROLLUP (d.YEAR_NUM, d.MONTH_NUM, c.SYMBOL)
ORDER BY d.YEAR_NUM, d.MONTH_NUM, c.SYMBOL;

-- A.3 Year-over-year variation: annual average price vs. prior year
-- LAG over an annual window per symbol
WITH ANNUAL AS (
    SELECT c.SYMBOL, d.YEAR_NUM,
           ROUND(AVG(f.CLOSE_PRICE), 2) AS AVG_PRICE
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY --AND c.IS_CURRENT = 'Y'
    GROUP BY c.SYMBOL, d.YEAR_NUM
)
SELECT SYMBOL, YEAR_NUM, AVG_PRICE,
       LAG(AVG_PRICE) OVER (PARTITION BY SYMBOL ORDER BY YEAR_NUM) AS PRIOR_YEAR_PRICE,
       ROUND((AVG_PRICE / NULLIF(LAG(AVG_PRICE) OVER (
           PARTITION BY SYMBOL ORDER BY YEAR_NUM), 0) - 1) * 100, 2) AS YOY_VARIATION_PCT
FROM ANNUAL
ORDER BY SYMBOL, YEAR_NUM;

-- A.4 Best and worst return quarter per symbol
-- RANK() within each company
WITH QUARTERLY AS (
    SELECT c.SYMBOL, d.YEAR_NUM, d.QUARTER_NUM,
           ROUND(AVG(f.DAILY_RETURN_PCT), 4) AS AVG_QUARTER_RETURN
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    WHERE f.DAILY_RETURN_PCT IS NOT NULL
    GROUP BY c.SYMBOL, d.YEAR_NUM, d.QUARTER_NUM
),
RANKED AS (
    SELECT SYMBOL, YEAR_NUM, QUARTER_NUM, AVG_QUARTER_RETURN,
           RANK() OVER (PARTITION BY SYMBOL ORDER BY AVG_QUARTER_RETURN DESC) AS BEST_RANK,
           RANK() OVER (PARTITION BY SYMBOL ORDER BY AVG_QUARTER_RETURN ASC) AS WORST_RANK
    FROM QUARTERLY
)
SELECT SYMBOL, YEAR_NUM || '-Q' || QUARTER_NUM AS QUARTER,
       AVG_QUARTER_RETURN,
       CASE WHEN BEST_RANK = 1 THEN 'BEST' END AS IS_BEST,
       CASE WHEN WORST_RANK = 1 THEN 'WORST' END AS IS_WORST
FROM RANKED
WHERE BEST_RANK = 1 OR WORST_RANK = 1
ORDER BY SYMBOL, YEAR_NUM;

-- A.5 52-week high and low (252-business-day window)
-- Identifies when a stock reaches its annual high/low
SELECT c.SYMBOL, d.FULL_DATE, f.CLOSE_PRICE,
       MAX(f.CLOSE_PRICE) OVER (PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
           ROWS BETWEEN 251 PRECEDING AND CURRENT ROW) AS HIGH_52W,
       MIN(f.CLOSE_PRICE) OVER (PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
           ROWS BETWEEN 251 PRECEDING AND CURRENT ROW) AS LOW_52W,
       CASE WHEN f.CLOSE_PRICE = MAX(f.CLOSE_PRICE) OVER (
           PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
           ROWS BETWEEN 251 PRECEDING AND CURRENT ROW)
           THEN 'HIGH_52W' END AS HITS_HIGH,
       CASE WHEN f.CLOSE_PRICE = MIN(f.CLOSE_PRICE) OVER (
           PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
           ROWS BETWEEN 251 PRECEDING AND CURRENT ROW)
           THEN 'LOW_52W' END AS HITS_LOW
FROM FACT_DAILY_QUOTE f
JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
ORDER BY c.SYMBOL, d.FULL_DATE;

-- A.6 Rolling volatility by quarter: VOLATILITY_20 average
-- Identifies high-/low-volatility regimes
SELECT c.SYMBOL, d.YEAR_NUM, d.QUARTER_NUM,
       ROUND(AVG(f.VOLATILITY_20), 4) AS AVG_QUARTER_VOLATILITY,
       ROUND(MAX(f.VOLATILITY_20), 4) AS MAX_QUARTER_VOLATILITY,
       RANK() OVER (PARTITION BY c.SYMBOL ORDER BY AVG(f.VOLATILITY_20) DESC) AS MOST_VOLATILE_RANK
FROM FACT_DAILY_QUOTE f
INNER JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
INNER JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
WHERE 1 = 1 AND f.VOLATILITY_20 IS NOT NULL
GROUP BY c.SYMBOL, d.YEAR_NUM, d.QUARTER_NUM
ORDER BY c.SYMBOL, d.YEAR_NUM, d.QUARTER_NUM;

-- ============================================================
-- SECTION B: PATTERN MATCHING (MATCH_RECOGNIZE)
-- ============================================================

-- B.1 Detect bullish streak: 3 or more consecutive days
-- with an increasing CLOSE_PRICE (each day > previous day)
SELECT SYMBOL, START_DATE, END_DATE, STREAK_DAYS, START_PRICE, END_PRICE,
       ROUND((END_PRICE / START_PRICE - 1) * 100, 2) AS STREAK_GAIN_PCT
FROM (
    SELECT c.SYMBOL, d.FULL_DATE AS TRADE_DATE, f.CLOSE_PRICE
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
)
MATCH_RECOGNIZE (
    PARTITION BY SYMBOL
    ORDER BY TRADE_DATE
    MEASURES FIRST(TRADE_DATE) AS START_DATE,
             LAST(TRADE_DATE) AS END_DATE,
             COUNT(*) AS STREAK_DAYS,
             FIRST(CLOSE_PRICE) AS START_PRICE,
             LAST(CLOSE_PRICE) AS END_PRICE
    ONE ROW PER MATCH
    AFTER MATCH SKIP TO NEXT ROW
    PATTERN (UP{3,})
    DEFINE UP AS CLOSE_PRICE > PREV(CLOSE_PRICE)
)
WHERE STREAK_DAYS >= 3
ORDER BY SYMBOL, START_DATE;

-- B.2 Detect bearish streak: 3 or more consecutive days
-- with a decreasing CLOSE_PRICE
SELECT SYMBOL, START_DATE, END_DATE, STREAK_DAYS, START_PRICE, END_PRICE,
       ROUND((END_PRICE / START_PRICE - 1) * 100, 2) AS STREAK_LOSS_PCT
FROM (
    SELECT c.SYMBOL, d.FULL_DATE AS TRADE_DATE, f.CLOSE_PRICE
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
)
MATCH_RECOGNIZE (
    PARTITION BY SYMBOL
    ORDER BY TRADE_DATE
    MEASURES FIRST(TRADE_DATE) AS START_DATE,
             LAST(TRADE_DATE) AS END_DATE,
             COUNT(*) AS STREAK_DAYS,
             FIRST(CLOSE_PRICE) AS START_PRICE,
             LAST(CLOSE_PRICE) AS END_PRICE
    ONE ROW PER MATCH
    AFTER MATCH SKIP TO NEXT ROW
    PATTERN (DOWN{3,})
    DEFINE DOWN AS CLOSE_PRICE < PREV(CLOSE_PRICE)
)
WHERE STREAK_DAYS >= 3
ORDER BY SYMBOL, START_DATE;

-- B.3 V-shaped recovery pattern: bearish streak followed by bullish streak
-- At least 3 declining days and at least 3 rising days
SELECT SYMBOL, DECLINE_START, BOTTOM, REBOUND_END,
       PREVIOUS_PEAK_PRICE, BOTTOM_PRICE, REBOUND_PRICE,
       ROUND((BOTTOM_PRICE / PREVIOUS_PEAK_PRICE - 1) * 100, 2) AS DECLINE_PCT,
       ROUND((REBOUND_PRICE / BOTTOM_PRICE - 1) * 100, 2) AS REBOUND_PCT
FROM (
    SELECT c.SYMBOL, d.FULL_DATE AS TRADE_DATE, f.CLOSE_PRICE
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
)
MATCH_RECOGNIZE (
    PARTITION BY SYMBOL
    ORDER BY TRADE_DATE
    MEASURES FIRST(DOWN.TRADE_DATE) AS DECLINE_START,
             LAST(DOWN.TRADE_DATE) AS BOTTOM,
             LAST(UP.TRADE_DATE) AS REBOUND_END,
             FIRST(DOWN.CLOSE_PRICE) AS PREVIOUS_PEAK_PRICE,
             LAST(DOWN.CLOSE_PRICE) AS BOTTOM_PRICE,
             LAST(UP.CLOSE_PRICE) AS REBOUND_PRICE
    ONE ROW PER MATCH
    AFTER MATCH SKIP TO NEXT ROW
    PATTERN (DOWN{3,} UP{3,})
    DEFINE DOWN AS CLOSE_PRICE < PREV(CLOSE_PRICE),
           UP AS CLOSE_PRICE > PREV(CLOSE_PRICE)
)
ORDER BY SYMBOL, DECLINE_START;

-- B.4 Golden Cross signal: first day when SMA_20 exceeds EMA_20
-- (positive crossover → bullish technical signal)
SELECT SYMBOL, CROSS_DATE, SMA_AT_CROSS, EMA_AT_CROSS, CLOSE_AT_CROSS
FROM (
    SELECT c.SYMBOL, d.FULL_DATE AS TRADE_DATE,
           f.SMA_20, f.EMA_20, f.CLOSE_PRICE
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
    WHERE f.SMA_20 IS NOT NULL AND f.EMA_20 IS NOT NULL
)
MATCH_RECOGNIZE (
    PARTITION BY SYMBOL
    ORDER BY TRADE_DATE
    MEASURES FIRST(CROSS.TRADE_DATE) AS CROSS_DATE,
             FIRST(CROSS.SMA_20) AS SMA_AT_CROSS,
             FIRST(CROSS.EMA_20) AS EMA_AT_CROSS,
             FIRST(CROSS.CLOSE_PRICE) AS CLOSE_AT_CROSS
    ONE ROW PER MATCH
    AFTER MATCH SKIP TO NEXT ROW
    PATTERN (BELOW CROSS)
    DEFINE BELOW AS SMA_20 <= EMA_20,
           CROSS AS SMA_20 > EMA_20
)
ORDER BY SYMBOL, CROSS_DATE;

-- B.5 Death Cross signal: first day when SMA_20 falls below EMA_20
-- (negative crossover → bearish technical signal)
SELECT SYMBOL, CROSS_DATE, SMA_AT_CROSS, EMA_AT_CROSS, CLOSE_AT_CROSS
FROM (
    SELECT c.SYMBOL, d.FULL_DATE AS TRADE_DATE,
           f.SMA_20, f.EMA_20, f.CLOSE_PRICE
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
    WHERE f.SMA_20 IS NOT NULL AND f.EMA_20 IS NOT NULL
)
MATCH_RECOGNIZE (
    PARTITION BY SYMBOL
    ORDER BY TRADE_DATE
    MEASURES FIRST(CROSS.TRADE_DATE) AS CROSS_DATE,
             FIRST(CROSS.SMA_20) AS SMA_AT_CROSS,
             FIRST(CROSS.EMA_20) AS EMA_AT_CROSS,
             FIRST(CROSS.CLOSE_PRICE) AS CLOSE_AT_CROSS
    ONE ROW PER MATCH
    AFTER MATCH SKIP TO NEXT ROW
    PATTERN (ABOVE CROSS)
    DEFINE ABOVE AS SMA_20 >= EMA_20,
           CROSS AS SMA_20 < EMA_20
)
ORDER BY SYMBOL, CROSS_DATE;

-- ============================================================
-- SECTION C: OLAP EXTENSIONS (ROLLUP, CUBE, NTILE)
-- ============================================================

-- C.1 Total trading volume with hierarchical ROLLUP
-- Sector > Symbol > Year — subtotals at each level
SELECT NVL(c.SECTOR, '(TOTAL)') AS SECTOR,
       NVL(c.SYMBOL, '(SECTOR)') AS SYMBOL,
       NVL(TO_CHAR(d.YEAR_NUM), '(YEARS)') AS YEAR,
       ROUND(SUM(f.VOLUME) / 1e6, 2) AS VOLUME_MILLIONS,
       ROUND(SUM(f.TRADED_VALUE) / 1e9, 4) AS TRADED_VALUE_BILLIONS
FROM FACT_DAILY_QUOTE f
JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
GROUP BY ROLLUP (c.SECTOR, c.SYMBOL, d.YEAR_NUM)
ORDER BY c.SECTOR, c.SYMBOL, d.YEAR_NUM;

-- C.2 Sector × Year CUBE: complete cross-analysis
-- Generates all possible combinations (sector, year, and total)
SELECT NVL(c.SECTOR, '(ALL)') AS SECTOR,
       NVL(TO_CHAR(d.YEAR_NUM), '(ALL)') AS YEAR,
       ROUND(AVG(f.CLOSE_PRICE), 2) AS AVG_PRICE,
       ROUND(AVG(f.DAILY_RETURN_PCT), 4) AS AVG_RETURN,
       ROUND(AVG(f.VOLATILITY_20), 4) AS AVG_VOLATILITY
FROM FACT_DAILY_QUOTE f
JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
WHERE f.DAILY_RETURN_PCT IS NOT NULL
GROUP BY CUBE (c.SECTOR, d.YEAR_NUM)
ORDER BY c.SECTOR, d.YEAR_NUM;

-- C.3 Stock classification by annual-return quartile
-- NTILE(4) within each year: Q1=worst, Q4=best
WITH ANNUAL AS (
    SELECT c.SYMBOL, c.SECTOR, d.YEAR_NUM,
           ROUND(AVG(f.DAILY_RETURN_PCT), 4) AS AVG_RETURN
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
    WHERE f.DAILY_RETURN_PCT IS NOT NULL
    GROUP BY c.SYMBOL, c.SECTOR, d.YEAR_NUM
)
SELECT SYMBOL, SECTOR, YEAR_NUM, AVG_RETURN,
       NTILE(4) OVER (PARTITION BY YEAR_NUM ORDER BY AVG_RETURN) AS QUARTILE,
       PERCENT_RANK() OVER (PARTITION BY YEAR_NUM ORDER BY AVG_RETURN) AS PERCENTILE,
       CUME_DIST() OVER (PARTITION BY YEAR_NUM ORDER BY AVG_RETURN) AS CUMULATIVE_DISTRIBUTION
FROM ANNUAL
ORDER BY YEAR_NUM, QUARTILE DESC, AVG_RETURN DESC;

-- C.4 Company ranking by total return in each sector
-- DENSE_RANK with RATIO_TO_REPORT for volume share
WITH TOTALS AS (
    SELECT c.SYMBOL, c.COMPANY_NAME, c.SECTOR,
           ROUND(SUM(f.TRADED_VALUE) / 1e9, 4) AS TOTAL_VALUE_BILLIONS,
           ROUND(AVG(f.DAILY_RETURN_PCT), 4) AS AVG_DAILY_RETURN,
           ROUND((LAST_VALUE(f.CLOSE_PRICE) OVER (
               PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
               ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
               / FIRST_VALUE(f.CLOSE_PRICE) OVER (
               PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
               ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
               - 1) * 100, 2) AS TOTAL_RETURN_PCT
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    GROUP BY c.SYMBOL, c.COMPANY_NAME, c.SECTOR,
             f.COMPANY_KEY, f.CLOSE_PRICE, f.DATE_KEY
),
GROUPED AS (
    SELECT SYMBOL, COMPANY_NAME, SECTOR,
           MAX(TOTAL_VALUE_BILLIONS) AS TOTAL_VALUE_BILLIONS,
           MAX(AVG_DAILY_RETURN) AS AVG_DAILY_RETURN,
           MAX(TOTAL_RETURN_PCT) AS TOTAL_RETURN_PCT
    FROM TOTALS
    GROUP BY SYMBOL, COMPANY_NAME, SECTOR
)
SELECT SYMBOL, COMPANY_NAME, SECTOR, TOTAL_VALUE_BILLIONS, TOTAL_RETURN_PCT,
       DENSE_RANK() OVER (
           PARTITION BY SECTOR ORDER BY TOTAL_RETURN_PCT DESC
       ) AS SECTOR_RANK,
       ROUND(RATIO_TO_REPORT(TOTAL_VALUE_BILLIONS) OVER (
           PARTITION BY SECTOR
       ) * 100, 2) AS VOLUME_SHARE_PCT
FROM GROUPED
ORDER BY SECTOR, SECTOR_RANK;

-- ============================================================
-- SECTION D: ADVANCED WINDOW FUNCTIONS
-- ============================================================

-- D.1 Maximum drawdown per symbol
-- Maximum percentage decline from historical peak to trough
WITH PEAKS AS (
    SELECT c.SYMBOL, d.FULL_DATE, f.CLOSE_PRICE,
           MAX(f.CLOSE_PRICE) OVER (
               PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
               ROWS UNBOUNDED PRECEDING
           ) AS HISTORICAL_PEAK
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
),
DRAWDOWNS AS (
    SELECT SYMBOL, FULL_DATE, CLOSE_PRICE, HISTORICAL_PEAK,
           ROUND((CLOSE_PRICE / HISTORICAL_PEAK - 1) * 100, 2) AS DRAWDOWN_PCT
    FROM PEAKS
)
SELECT SYMBOL, MIN(DRAWDOWN_PCT) AS MAX_DRAWDOWN_PCT,
       FULL_DATE AS MAX_DRAWDOWN_DATE
FROM DRAWDOWNS
GROUP BY SYMBOL, FULL_DATE
HAVING DRAWDOWN_PCT = (
    SELECT MIN(d2.DRAWDOWN_PCT)
    FROM DRAWDOWNS d2
    WHERE d2.SYMBOL = DRAWDOWNS.SYMBOL
)
ORDER BY MAX_DRAWDOWN_PCT;

-- D.2 Return correlation between stock pairs
-- Uses the CORR() function with a self-join
-- (requires access to two rows from the same day → self-join)
WITH RETURNS AS (
    SELECT c.SYMBOL, f.DATE_KEY, f.DAILY_RETURN_PCT
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    WHERE f.DAILY_RETURN_PCT IS NOT NULL
)
SELECT a.SYMBOL AS SYMBOL_A, b.SYMBOL AS SYMBOL_B,
       COUNT(*) AS COMMON_DAYS,
       ROUND(CORR(a.DAILY_RETURN_PCT, b.DAILY_RETURN_PCT), 4) AS CORRELATION
FROM RETURNS a
JOIN RETURNS b ON b.DATE_KEY = a.DATE_KEY AND b.SYMBOL > a.SYMBOL
GROUP BY a.SYMBOL, b.SYMBOL
HAVING COUNT(*) >= 100
ORDER BY ABS(CORR(a.DAILY_RETURN_PCT, b.DAILY_RETURN_PCT)) DESC;

-- D.3 Sector momentum: volume-weighted average return
-- in a rolling 60-business-day window
-- Identifies which sectors lead the market at each point in time
WITH BASE AS (
    SELECT c.SECTOR, d.FULL_DATE, f.DATE_KEY,
           SUM(f.DAILY_RETURN_PCT * f.VOLUME) OVER (
               PARTITION BY c.SECTOR ORDER BY f.DATE_KEY
               ROWS BETWEEN 59 PRECEDING AND CURRENT ROW
           ) AS WEIGHTED_RETURN_60D,
           SUM(f.VOLUME) OVER (
               PARTITION BY c.SECTOR ORDER BY f.DATE_KEY
               ROWS BETWEEN 59 PRECEDING AND CURRENT ROW
           ) AS VOLUME_60D,
           COUNT(*) OVER (
               PARTITION BY c.SECTOR ORDER BY f.DATE_KEY
               ROWS BETWEEN 59 PRECEDING AND CURRENT ROW
           ) AS WINDOW_ROWS
    FROM FACT_DAILY_QUOTE f
    JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
    JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
    WHERE f.DAILY_RETURN_PCT IS NOT NULL
)
SELECT SECTOR, FULL_DATE,
       ROUND(WEIGHTED_RETURN_60D / NULLIF(VOLUME_60D, 0), 6) AS MOMENTUM_60D,
       RANK() OVER (
           PARTITION BY DATE_KEY
           ORDER BY WEIGHTED_RETURN_60D / NULLIF(VOLUME_60D, 0) DESC
       ) AS SECTOR_RANK
FROM BASE
WHERE WINDOW_ROWS >= 60
ORDER BY SECTOR, FULL_DATE;

-- D.4 Significant bullish gap days (gap-up > 2%)
-- Today's OPEN_PRICE > yesterday's CLOSE_PRICE by more than 2%
-- A "gap" is a price jump between the previous close
-- and the following day's open — a signal of relevant news
SELECT c.SYMBOL, d.FULL_DATE AS GAP_DATE,
       f.OPEN_PRICE AS TODAY_OPEN,
       LAG(f.CLOSE_PRICE) OVER (
           PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
       ) AS YESTERDAY_CLOSE,
       ROUND((f.OPEN_PRICE / NULLIF(LAG(f.CLOSE_PRICE) OVER (
           PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
       ), 0) - 1) * 100, 2) AS GAP_PCT
FROM FACT_DAILY_QUOTE f
JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY AND c.IS_CURRENT = 'Y'
JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
WHERE (f.OPEN_PRICE / NULLIF(LAG(f.CLOSE_PRICE) OVER (
    PARTITION BY f.COMPANY_KEY ORDER BY f.DATE_KEY
), 0) - 1) * 100 > 2
ORDER BY c.SYMBOL, d.FULL_DATE;

-- D.5 Summary statistics by symbol (executive view)
-- Combines multiple metrics in a single query
SELECT c.SYMBOL, c.COMPANY_NAME, c.SECTOR,
       MIN(d.FULL_DATE) AS FIRST_QUOTE,
       MAX(d.FULL_DATE) AS LAST_QUOTE,
       COUNT(*) AS TOTAL_DAYS,
       ROUND(MIN(f.CLOSE_PRICE), 2) AS HISTORICAL_MIN_PRICE,
       ROUND(MAX(f.CLOSE_PRICE), 2) AS HISTORICAL_MAX_PRICE,
       ROUND(AVG(f.CLOSE_PRICE), 2) AS AVG_PRICE,
       ROUND(MEDIAN(f.CLOSE_PRICE), 2) AS MEDIAN_PRICE,
       ROUND(STDDEV(f.CLOSE_PRICE), 2) AS PRICE_STD_DEV,
       ROUND(AVG(f.DAILY_RETURN_PCT), 4) AS AVG_DAILY_RETURN,
       ROUND(STDDEV(f.DAILY_RETURN_PCT), 4) AS DAILY_RETURN_STD_DEV,
       ROUND(AVG(f.VOLATILITY_20), 4) AS AVG_VOLATILITY,
       ROUND(SUM(f.TRADED_VALUE) / 1e9, 2) AS TOTAL_VALUE_BILLIONS
FROM FACT_DAILY_QUOTE f
JOIN DIM_COMPANY c ON c.COMPANY_KEY = f.COMPANY_KEY --AND c.IS_CURRENT = 'Y'
JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
GROUP BY c.SYMBOL, c.COMPANY_NAME, c.SECTOR
ORDER BY c.SECTOR, c.SYMBOL;