-- Stock Market DW
-- DATA PROFILING (queries)

-- DESCRIPTIVE FIELDS: domain, absolute distribution, and %
-- SYMBOL (STG_DAILY_PRICES)
SELECT
    SYMBOL,
    COUNT(*) AS ABS_FREQ,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS FREQ_PCT
FROM
    STG_DAILY_PRICES
GROUP BY
    SYMBOL
ORDER BY
    ABS_FREQ DESC;

-- SECTOR (STG_COMPANY_OVERVIEW)
SELECT
    SECTOR,
    COUNT(*) AS ABS_FREQ,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS FREQ_PCT
FROM
    STG_COMPANY_OVERVIEW
GROUP BY
    SECTOR
ORDER BY
    ABS_FREQ DESC;

-- INDUSTRY, EXCHANGE, COUNTRY: same template
SELECT
    EXCHANGE,
    COUNT(*) AS ABS_FREQ,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS FREQ_PCT
FROM
    STG_COMPANY_OVERVIEW
GROUP BY
    EXCHANGE
ORDER BY
    ABS_FREQ DESC;

SELECT
    INDUSTRY,
    COUNT(*) AS ABS_FREQ,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS FREQ_PCT
FROM
    STG_COMPANY_OVERVIEW
GROUP BY
    INDUSTRY
ORDER BY
    ABS_FREQ DESC;

-- Distribution of price rows by SECTOR (cross-source comparison)
SELECT
    o.SECTOR,
    COUNT(*) AS PRICE_ROWS,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS PCT
FROM
    STG_DAILY_PRICES p
INNER JOIN
    STG_COMPANY_OVERVIEW o ON (o.SYMBOL = p.SYMBOL)
GROUP BY
    o.SECTOR
ORDER BY
    PRICE_ROWS DESC;

-- NUMERIC FIELDS: min, max, average, median, standard deviation
SELECT
    'OPEN_PRICE' AS FIELD,
    MIN(OPEN_PRICE) AS MINIMUM,
    MAX(OPEN_PRICE) AS MAXIMUM,
    ROUND(AVG(OPEN_PRICE), 4) AS AVERAGE,
    ROUND(MEDIAN(OPEN_PRICE), 4) AS MEDIAN,
    ROUND(STDDEV(OPEN_PRICE), 4) AS STD_DEV,
    COUNT(*) AS N,
    SUM(CASE WHEN OPEN_PRICE IS NULL THEN 1 ELSE 0 END) AS NULLS
FROM
    STG_DAILY_PRICES
UNION ALL
SELECT
    'HIGH_PRICE',
    MIN(HIGH_PRICE),
    MAX(HIGH_PRICE),
    ROUND(AVG(HIGH_PRICE), 5),
    ROUND(MEDIAN(HIGH_PRICE), 5),
    ROUND(STDDEV(HIGH_PRICE), 5),
    COUNT(*),
    SUM(CASE WHEN HIGH_PRICE IS NULL THEN 1 ELSE 0 END)
FROM
    STG_DAILY_PRICES
UNION ALL
SELECT
    'LOW_PRICE',
    MIN(LOW_PRICE),
    MAX(LOW_PRICE),
    ROUND(AVG(LOW_PRICE), 5),
    ROUND(MEDIAN(LOW_PRICE), 5),
    ROUND(STDDEV(LOW_PRICE), 5),
    COUNT(*),
    SUM(CASE WHEN LOW_PRICE IS NULL THEN 1 ELSE 0 END)
FROM
    STG_DAILY_PRICES
UNION ALL
SELECT
    'CLOSE_PRICE',
    MIN(CLOSE_PRICE),
    MAX(CLOSE_PRICE),
    ROUND(AVG(CLOSE_PRICE), 5),
    ROUND(MEDIAN(CLOSE_PRICE), 5),
    ROUND(STDDEV(CLOSE_PRICE), 5),
    COUNT(*),
    SUM(CASE WHEN CLOSE_PRICE IS NULL THEN 1 ELSE 0 END)
FROM
    STG_DAILY_PRICES
UNION ALL
SELECT
    'VOLUME',
    MIN(VOLUME),
    MAX(VOLUME),
    ROUND(AVG(VOLUME), 2),
    ROUND(MEDIAN(VOLUME), 2),
    ROUND(STDDEV(VOLUME), 2),
    COUNT(*),
    SUM(CASE WHEN VOLUME IS NULL THEN 1 ELSE 0 END)
FROM
    STG_DAILY_PRICES;

-- Statistics by company symbol
SELECT
    SYMBOL,
    MIN(CLOSE_PRICE) AS MIN_CLOSE,
    MAX(CLOSE_PRICE) AS MAX_CLOSE,
    ROUND(AVG(CLOSE_PRICE), 2) AS AVG_CLOSE,
    MIN(TRADE_DATE) AS FIRST_DATE,
    MAX(TRADE_DATE) AS LAST_DATE,
    COUNT(*) AS TRADING_DAYS
FROM
    STG_DAILY_PRICES
GROUP BY
    SYMBOL
ORDER BY
    SYMBOL;

-- HISTOGRAMS / BINNING with WIDTH_BUCKET
-- CLOSE_PRICE histogram in 10 fixed-width bins
WITH RANGES AS (
    SELECT
        MIN(CLOSE_PRICE) AS LOW,
        MAX(CLOSE_PRICE) AS HIGH
    FROM
        STG_DAILY_PRICES
)
SELECT
    WIDTH_BUCKET(p.CLOSE_PRICE, r.LOW, r.HIGH, 10) AS BIN,
    MIN(p.CLOSE_PRICE) AS FROM_VALUE,
    MAX(p.CLOSE_PRICE) AS TO_VALUE,
    COUNT(*) AS FREQUENCY,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS PCT
FROM
    STG_DAILY_PRICES p
    CROSS JOIN RANGES r
GROUP BY
    WIDTH_BUCKET(p.CLOSE_PRICE, r.LOW, r.HIGH, 10)
ORDER BY
    BIN;

-- VOLUME histogram on a logarithmic scale (log10 binning)
SELECT
    TRUNC(LOG(10, NULLIF(VOLUME, 0))) AS LOG10_BIN,
    POWER(10, TRUNC(LOG(10, NULLIF(VOLUME, 0)))) AS FROM_VALUE,
    POWER(10, TRUNC(LOG(10, NULLIF(VOLUME, 0))) + 1) AS TO_VALUE,
    COUNT(*) AS FREQUENCY,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS PCT
FROM
    STG_DAILY_PRICES
GROUP BY
    TRUNC(LOG(10, NULLIF(VOLUME, 0)))
ORDER BY
    LOG10_BIN;

-- Daily return distribution (1% binning between -10% and +10%)
WITH RETURNS AS (
    SELECT
        SYMBOL,
        TRADE_DATE,
        (CLOSE_PRICE / LAG(CLOSE_PRICE) OVER (
            PARTITION BY SYMBOL
            ORDER BY TRADE_DATE
        ) - 1) * 100 AS RETURN_PCT
    FROM
        STG_DAILY_PRICES
)
SELECT
    WIDTH_BUCKET(RETURN_PCT, -10, 10, 20) AS BIN,
    COUNT(*) AS FREQUENCY
FROM
    RETURNS
WHERE
    RETURN_PCT IS NOT NULL
GROUP BY
    WIDTH_BUCKET(RETURN_PCT, -10, 10, 20)
ORDER BY
    BIN;

-- Identifying candidate keys
-- (SYMBOL, TRADE_DATE) is a key if TOTAL = DISTINCT and there are no nulls
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT SYMBOL || '|' || TO_CHAR(TRADE_DATE, 'YYYYMMDD')) AS DISTINCT_COMBINATIONS,
    SUM(CASE WHEN SYMBOL IS NULL OR TRADE_DATE IS NULL THEN 1 ELSE 0 END) AS NULLS
FROM
    STG_DAILY_PRICES;

-- Exact duplicates of the candidate key (must return 0 rows)
SELECT
    SYMBOL,
    TRADE_DATE,
    COUNT(*) AS OCCURRENCES
FROM
    STG_DAILY_PRICES
GROUP BY
    SYMBOL,
    TRADE_DATE
HAVING COUNT(*) > 1;

-- SYMBOL as a key in company tables
SELECT
    COUNT(*) AS TOTAL,
    COUNT(DISTINCT SYMBOL) AS DISTINCT_VALUES
FROM
    STG_COMPANY_OVERVIEW;

SELECT
    COUNT(*) AS TOTAL,
    COUNT(DISTINCT SYMBOL) AS DISTINCT_VALUES
FROM
    STG_SP500_COMPONENTS;

-- Implicit referential integrity between sources:
-- symbols with prices but without company metadata (must be 0)
SELECT DISTINCT
    p.SYMBOL
FROM
    STG_DAILY_PRICES p
WHERE
    NOT EXISTS (
        SELECT 1
        FROM STG_COMPANY_OVERVIEW o
        WHERE o.SYMBOL = p.SYMBOL
    );

-- Non-positive prices or volumes (expected: 0)
SELECT
    COUNT(*) AS NON_POSITIVE_VALUES
FROM
    STG_DAILY_PRICES
WHERE
    OPEN_PRICE <= 0
    OR HIGH_PRICE <= 0
    OR LOW_PRICE <= 0
    OR CLOSE_PRICE <= 0
    OR VOLUME < 0;

-- Calendar gaps: business days without quotes per symbol
SELECT
    SYMBOL,
    COUNT(*) AS DAYS,
    MAX(TRADE_DATE) - MIN(TRADE_DATE) AS CALENDAR_DAY_RANGE,
    ROUND(COUNT(*) / ((MAX(TRADE_DATE) - MIN(TRADE_DATE)) * 5 / 7), 4) AS APPROX_COVERAGE
FROM
    STG_DAILY_PRICES
GROUP BY
    SYMBOL
ORDER BY
    APPROX_COVERAGE;

-- For analysis hierarchies
-- Time hierarchy: cardinality by level
SELECT
    COUNT(DISTINCT EXTRACT(YEAR FROM TRADE_DATE)) AS YEARS,
    COUNT(DISTINCT TO_CHAR(TRADE_DATE, 'YYYY-Q')) AS QUARTERS,
    COUNT(DISTINCT TO_CHAR(TRADE_DATE, 'YYYY-MM')) AS MONTHS,
    COUNT(DISTINCT TRADE_DATE) AS DAYS
FROM
    STG_DAILY_PRICES;

-- Organizational hierarchy: Sector > Industry > Company
SELECT
    SECTOR,
    INDUSTRY,
    COUNT(*) AS COMPANIES
FROM
    STG_COMPANY_OVERVIEW
GROUP BY
    ROLLUP (SECTOR, INDUSTRY)
ORDER BY
    SECTOR,
    INDUSTRY;

SELECT * FROM STG_SP500_COMPONENTS;