-- DW Bursátil
-- DATA PROFILING (queries)

-- CAMPOS DESCRIPTIVOS: dominio, distribución absoluta y %
-- SYMBOL (STG_DAILY_PRICES)
SELECT
    SYMBOL,
    COUNT(*) AS FREQ_ABS,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS FREQ_PCT
FROM
    STG_DAILY_PRICES
GROUP BY
    SYMBOL
ORDER BY
    FREQ_ABS DESC;

-- SECTOR (STG_COMPANY_OVERVIEW)
SELECT
    SECTOR,
    COUNT(*) AS FREQ_ABS,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS FREQ_PCT
FROM
    STG_COMPANY_OVERVIEW
GROUP BY
    SECTOR
ORDER BY
    FREQ_ABS DESC;

-- INDUSTRY, EXCHANGE, COUNTRY: misma plantilla
SELECT
    EXCHANGE,
    COUNT(*) AS FREQ_ABS,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS FREQ_PCT
FROM
    STG_COMPANY_OVERVIEW
GROUP BY
    EXCHANGE
ORDER BY
    FREQ_ABS DESC;

SELECT
    INDUSTRY,
    COUNT(*) AS FREQ_ABS,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS FREQ_PCT
FROM 
    STG_COMPANY_OVERVIEW
GROUP BY
    INDUSTRY
ORDER BY
    FREQ_ABS DESC;

-- Distribución de filas de precios por SECTOR (cruce de fuentes)
SELECT
    o.SECTOR,
    COUNT(*) AS FILAS_PRECIOS,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS PCT
FROM
    STG_DAILY_PRICES p
INNER JOIN
    STG_COMPANY_OVERVIEW o ON (o.SYMBOL = p.SYMBOL)
GROUP  BY
    o.SECTOR
ORDER BY
    FILAS_PRECIOS DESC;

-- CAMPOS NUMÉRICOS: min, max, promedio, mediana, desviación
SELECT
    'OPEN_PRICE'  AS CAMPO,
    MIN(OPEN_PRICE)  AS MINIMO,
    MAX(OPEN_PRICE)  AS MAXIMO,
    ROUND(AVG(OPEN_PRICE),4)  AS PROMEDIO,
    ROUND(MEDIAN(OPEN_PRICE),4)  AS MEDIANA,
    ROUND(STDDEV(OPEN_PRICE),4) AS DESV_EST, COUNT(*) AS N, 
    SUM(CASE WHEN OPEN_PRICE IS NULL THEN 1 ELSE 0 END) AS NULOS
FROM
    STG_DAILY_PRICES
UNION ALL
SELECT
    'HIGH_PRICE', MIN(HIGH_PRICE),
    MAX(HIGH_PRICE),
    ROUND(AVG(HIGH_PRICE),5),
    ROUND(MEDIAN(HIGH_PRICE),5),
    ROUND(STDDEV(HIGH_PRICE),5),
    COUNT(*),
    SUM(CASE WHEN HIGH_PRICE IS NULL THEN 1 ELSE 0 END)
FROM
    STG_DAILY_PRICES
UNION ALL
SELECT
    'LOW_PRICE',
    MIN(LOW_PRICE),
    MAX(LOW_PRICE),
    ROUND(AVG(LOW_PRICE),5),
    ROUND(MEDIAN(LOW_PRICE),5),
    ROUND(STDDEV(LOW_PRICE),5),
    COUNT(*),
    SUM(CASE WHEN LOW_PRICE IS NULL THEN 1 ELSE 0 END)
FROM
    STG_DAILY_PRICES
UNION ALL
SELECT
    'CLOSE_PRICE',
    MIN(CLOSE_PRICE),
    MAX(CLOSE_PRICE),
    ROUND(AVG(CLOSE_PRICE), 5),
    ROUND(MEDIAN(CLOSE_PRICE),5),
    ROUND(STDDEV(CLOSE_PRICE),5),
    COUNT(*),
    SUM(CASE WHEN CLOSE_PRICE IS NULL THEN 1 ELSE 0 END)
FROM
    STG_DAILY_PRICES
UNION ALL
SELECT
    'VOLUME',
    MIN(VOLUME),
    MAX(VOLUME),
    ROUND(AVG(VOLUME),2),
    ROUND(MEDIAN(VOLUME),2),
    ROUND(STDDEV(VOLUME),2),
    COUNT(*),
    SUM(CASE WHEN VOLUME IS NULL THEN 1 ELSE 0 END)
FROM
    STG_DAILY_PRICES;

-- Estadísticas por símbolo de empresa
SELECT
    SYMBOL,
    MIN(CLOSE_PRICE) AS MIN_CLOSE,
    MAX(CLOSE_PRICE) AS MAX_CLOSE,
    ROUND(AVG(CLOSE_PRICE),2) AS AVG_CLOSE,
    MIN(TRADE_DATE) AS PRIMERA_FECHA,
    MAX(TRADE_DATE) AS ULTIMA_FECHA,
    COUNT(*) AS DIAS_COTIZADOS
FROM
    STG_DAILY_PRICES
GROUP BY
    SYMBOL
ORDER BY
    SYMBOL;

-- HISTOGRAMAS / BINNING con WIDTH_BUCKET
-- Histograma de CLOSE_PRICE en 10 bins de ancho fijo
WITH RANGOS AS (
    SELECT
        MIN(CLOSE_PRICE) AS LO,
        MAX(CLOSE_PRICE) AS HI
    FROM
        STG_DAILY_PRICES
)
SELECT
    WIDTH_BUCKET(p.CLOSE_PRICE, r.LO, r.HI, 10) AS BIN,
    MIN(p.CLOSE_PRICE) AS DESDE,
    MAX(p.CLOSE_PRICE) AS HASTA,
    COUNT(*) AS FRECUENCIA,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS PCT
FROM
    STG_DAILY_PRICES p
    CROSS JOIN RANGOS r
GROUP BY
    WIDTH_BUCKET(p.CLOSE_PRICE, r.LO, r.HI, 10)
ORDER BY
    BIN;

-- Histograma de VOLUME en escala logarítmica (binning log10)
SELECT
    TRUNC(LOG(10, NULLIF(VOLUME,0))) AS LOG10_BIN,
    POWER(10, TRUNC(LOG(10, NULLIF(VOLUME,0)))) AS DESDE,
    POWER(10, TRUNC(LOG(10, NULLIF(VOLUME,0))) + 1) AS HASTA,
    COUNT(*) AS FRECUENCIA,
    ROUND(RATIO_TO_REPORT(COUNT(*)) OVER () * 100, 2) AS PCT
FROM
    STG_DAILY_PRICES
GROUP BY
    TRUNC(LOG(10, NULLIF(VOLUME,0)))
ORDER BY
    LOG10_BIN;

-- Distribución del retorno diario (binning de 1% entre -10% y +10%)
WITH RET AS (
    SELECT
        SYMBOL,
        TRADE_DATE,
        (CLOSE_PRICE / LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL
            ORDER BY TRADE_DATE) - 1) * 100 AS RET_PCT
    FROM
        STG_DAILY_PRICES
)
SELECT
    WIDTH_BUCKET(RET_PCT, -10, 10, 20) AS BIN,
    COUNT(*) AS FRECUENCIA
FROM
    RET
WHERE
    RET_PCT IS NOT NULL
GROUP BY
    WIDTH_BUCKET(RET_PCT, -10, 10, 20)
ORDER BY
    BIN;

-- indentificando llaves candidatas
-- (SYMBOL, TRADE_DATE) es llave si TOTAL = DISTINTOS y sin nulos
SELECT
    COUNT(*) AS TOTAL_FILAS,
    COUNT(DISTINCT SYMBOL || '|' || TO_CHAR(TRADE_DATE,'YYYYMMDD')) AS COMBINACIONES_DISTINTAS,
    SUM(CASE WHEN SYMBOL IS NULL OR TRADE_DATE IS NULL THEN 1 ELSE 0 END) AS NULOS
FROM
    STG_DAILY_PRICES;

-- Duplicados exactos de la llave candidata (debe retornar 0 filas)
SELECT
    SYMBOL,
    TRADE_DATE,
    COUNT(*) AS REPETICIONES
FROM
    STG_DAILY_PRICES
GROUP BY
    SYMBOL,
    TRADE_DATE
HAVING COUNT(*) > 1;

-- SYMBOL como llave en las tablas de empresa
SELECT
    COUNT(*) AS TOTAL,
    COUNT(DISTINCT SYMBOL) AS DISTINTOS
FROM
    STG_COMPANY_OVERVIEW;
SELECT
    COUNT(*) AS TOTAL,
    COUNT(DISTINCT SYMBOL) AS DISTINTOS
FROM
    STG_SP500_COMPONENTS;

-- Integridad referencial implícita entre fuentes:
-- símbolos con precios pero sin metadatos de empresa (debe ser 0)
SELECT
    DISTINCT p.SYMBOL
FROM
    STG_DAILY_PRICES p
WHERE
    NOT EXISTS (SELECT 1 FROM STG_COMPANY_OVERVIEW o
        WHERE o.SYMBOL = p.SYMBOL);

-- Precios o volúmenes no positivos (esperado: 0)
SELECT
    COUNT(*) AS VALORES_NO_POSITIVOS
FROM
    STG_DAILY_PRICES
WHERE
    OPEN_PRICE <= 0
    OR HIGH_PRICE <= 0
    OR LOW_PRICE <= 0
    OR  CLOSE_PRICE <= 0
    OR VOLUME < 0;

-- Huecos de calendario: días hábiles sin cotización por símbolo
SELECT
    SYMBOL,
    COUNT(*) AS DIAS, 
    MAX(TRADE_DATE) - MIN(TRADE_DATE) AS RANGO_DIAS_CALENDARIO,
    ROUND(COUNT(*) / ((MAX(TRADE_DATE) - MIN(TRADE_DATE)) * 5/7), 4) AS COBERTURA_APROX
FROM
    STG_DAILY_PRICES
GROUP BY
    SYMBOL
ORDER BY
    COBERTURA_APROX;

-- Para jerarquias de analisis
-- Jerarquía temporal: cardinalidad por nivel
SELECT
    COUNT(DISTINCT EXTRACT(YEAR FROM TRADE_DATE)) AS ANIOS,
    COUNT(DISTINCT TO_CHAR(TRADE_DATE,'YYYY-Q')) AS TRIMESTRES,
    COUNT(DISTINCT TO_CHAR(TRADE_DATE,'YYYY-MM')) AS MESES,
    COUNT(DISTINCT TRADE_DATE) AS DIAS
FROM
    STG_DAILY_PRICES;

-- Jerarquía organizacional: Sector > Industria > Compañía
SELECT
    SECTOR,
    INDUSTRY,
    COUNT(*) AS COMPANIAS
FROM
    STG_COMPANY_OVERVIEW
GROUP BY
    ROLLUP (SECTOR, INDUSTRY)
ORDER BY
    SECTOR,
    INDUSTRY
;


SELECT * FROM STG_SP500_COMPONENTS;
