"""
load_to_oracle.py - Loads CSV files generated by the pipeline into Oracle Autonomous DB.

Connection via Oracle Wallet (thin mode, without Oracle Client intalled).
Connection variables are read from the .env file:
    - ORACLE_WALLET_DIR - path to the wallet (.zip or extracted folder)
    - ORACLE_WALLET_PASSWORD - wallet password (leave empty if not applicable)
    - ORACLE_DSN - alias in tnsnames.ora (optional: auto-detected if empty)
    - ORACLE_USER - Oracle user, e.g. "ADMIN"
    - ORACLE_PASSWORD - Oracle user password

Files loaded (from output/):
    stg_daily_prices.csv        → TRUNCATE + INSERT into STG_DAILY_PRICES
    stg_company_overview.csv    → TRUNCATE + INSERT into STG_COMPANY_OVERVIEW
    stg_sp500_components.csv    → TRUNCATE + INSERT into STG_SP500_COMPONENTS

Usage:
    python -m stock_market_dw.pipeline.load_to_oracle
"""

from __future__ import annotations

import math
import os
import pathlib
import re
import sys
import zipfile

import pandas as pd
from dotenv import load_dotenv

load_dotenv()

_ROOT = pathlib.Path(__file__).parents[3]
_OUTPUT = _ROOT / "output"
_BATCH = 500

################## wallet helpers ##################

def _ensure_wallet_dir(wallet: pathlib.Path) -> pathlib.Path:
    """Ensures the wallet is in a directory (extracts the .zip if needed).
    
    oracledb thin mode requires a directory with ewallet.pem / cwallet.sso;
    it does not accept .zip files directly as wallet_location.
    """
    if wallet.is_dir():
        return wallet

    if wallet.suffix.lower() != ".zip":
        sys.exit(f"ORACLE_WALLET_DIR is not a .zip or a directory: {wallet}")

    destination = wallet.parent / wallet.stem
    if not destination.exists():
        try:
            print(f"Extracting wallet to {destination}...")
            with zipfile.ZipFile(wallet) as zip_file:
                zip_file.extractall(destination)
        except PermissionError:
            sys.exit(
                f"\nPermission denied while reading: {wallet}\n"
                "macOS blocks ~/Downloads. Move the wallet to another directory"
                "Then update ORACLE_WALLET_DIR in .env."
            )
    return destination


