-- DIM_DATE: Jerarquia Anio > Trimestre > Mes > Dia | Anio > Semana > Dia
CREATE TABLE DIM_DATE (
    DATE_KEY NUMBER(8) NOT NULL,   -- YYYYMMDD
    FULL_DATE DATE NOT NULL,
    DAY_OF_MONTH NUMBER(2) NOT NULL,
    DAY_NAME VARCHAR2(12) NOT NULL,
    DAY_OF_WEEK NUMBER(1) NOT NULL,   -- 1=Lunes ... 7=Domingo (ISO)
    WEEK_OF_YEAR NUMBER(2) NOT NULL,
    MONTH_NUM NUMBER(2) NOT NULL,
    MONTH_NAME VARCHAR2(12) NOT NULL,
    QUARTER_NUM NUMBER(1) NOT NULL,
    YEAR_NUM NUMBER(4) NOT NULL,
    IS_MONTH_END CHAR(1) DEFAULT 'N' NOT NULL,
    IS_YEAR_END CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY),
    CONSTRAINT UQ_DIM_DATE_FULL UNIQUE (FULL_DATE)
);

-- DIM_COMPANY: Sector > Industria > Sub-Industria > Compania (SCD Tipo 2)
CREATE TABLE DIM_COMPANY (
    COMPANY_KEY NUMBER GENERATED ALWAYS AS IDENTITY,
    SYMBOL VARCHAR2(10) NOT NULL,   -- llave natural
    COMPANY_NAME VARCHAR2(200) NOT NULL,
    EXCHANGE VARCHAR2(20),
    SECTOR VARCHAR2(100) NOT NULL,
    INDUSTRY VARCHAR2(150),
    SUB_INDUSTRY VARCHAR2(150),
    COUNTRY VARCHAR2(50),
    VALID_FROM DATE DEFAULT DATE '1900-01-01' NOT NULL,
    VALID_TO DATE DEFAULT DATE '9999-12-31' NOT NULL,
    IS_CURRENT CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_DIM_COMPANY PRIMARY KEY (COMPANY_KEY),
    CONSTRAINT CK_DIM_COMPANY_CURR CHECK (IS_CURRENT IN ('Y','N'))
);

-- FACT_DAILY_QUOTE: grano = 1 fila por simbolo por dia de cotizacion
CREATE TABLE FACT_DAILY_QUOTE (
    DATE_KEY NUMBER(8) NOT NULL,
    COMPANY_KEY NUMBER NOT NULL,
    OPEN_PRICE NUMBER(12,4) NOT NULL,
    HIGH_PRICE NUMBER(12,4) NOT NULL,
    LOW_PRICE NUMBER(12,4) NOT NULL,
    CLOSE_PRICE NUMBER(12,4) NOT NULL,
    VOLUME NUMBER(15) NOT NULL,
    TRADED_VALUE NUMBER(20,2), 
    DAILY_RETURN_PCT NUMBER(10,4),
    INTRADAY_RANGE NUMBER(12,4),
    SMA_20 NUMBER(12,4),
    EMA_20 NUMBER(12,4),
    VOLATILITY_20 NUMBER(10,4),
    CONSTRAINT PK_FACT_DAILY_QUOTE PRIMARY KEY (DATE_KEY, COMPANY_KEY),
    CONSTRAINT FK_FACT_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE (DATE_KEY),
    CONSTRAINT FK_FACT_COMPANY FOREIGN KEY (COMPANY_KEY) REFERENCES DIM_COMPANY (COMPANY_KEY)
);